const languages = [
  { name: "HTML", slug: "html", extension: "html" },
  { name: "JavaScript", slug: "javascript", extension: "js" },
  { name: "Java", slug: "java", extension: "java" },
  { name: "Python", slug: "python", extension: "py" },
  { name: "C", slug: "c", extension: "c" },
  { name: "C++", slug: "cpp", extension: "cpp" },
  { name: "Assembly", slug: "assembly", extension: "asm" },
  { name: "Ruby", slug: "ruby", extension: "rb" },
  { name: "Go", slug: "go", extension: "go" },
  { name: "Bash", slug: "bash", extension: "sh" },
  { name: "Lua", slug: "lua", extension: "lua" },
  { name: "Scala", slug: "scala", extension: "scala" },
  { name: "PHP", slug: "php", extension: "php" },
  { name: "C#", slug: "csharp", extension: "cs" },
  { name: "Perl", slug: "perl", extension: "pl" },
  { name: "Go", slug: "go", extension: "go" },
  { name: "Visual Basic (VB.NET)", slug: "vb", extension: "vb" },
  { name: "TypeScript", slug: "typescript", extension: "ts" },
  { name: "Kotlin", slug: "kotlin", extension: "kt" },
  { name: "Pascal", slug: "pascal", extension: "pas" },
  { name: "Rust", slug: "rust", extension: "rs" },
  { name: "Swift", slug: "swift", extension: "swift" },
  { name: "Objective-C", slug: "objectivec", theme: "objective-c", extension: "m" },
  { name: "CoffeeScript", slug: "coffeescript", extension: "coffee" },
  { name: "MySQL", slug: "mysql", theme: "sql" },
  { name: "MariaDB", slug: "mariadb", theme: "sql", extension: "sql" },
  { name: "Microsoft SQL Server", slug: "sqlserver", theme: "sql", extension: "sql" },
  { name: "SQLite", slug: "sqlite", theme: "sql", extension: "sql" },
  { name: "Oracle Database", slug: "oracle-database", theme: "sql", extension: "sql" },
  { name: "Redis", slug: "redis", theme: "sql", extension: "sql" },
  { name: "MongoDB", slug: "mongodb", theme: "javascript", extension: "js" },
];

export default languages;
