const languages = [
  { name: "Java", slug: "java" },
  { name: "Python", slug: "python" },
  { name: "C", slug: "c" },
  { name: "C++", slug: "cpp" },
  { name: "JavaScript", slug: "javascript" },
  { name: "Lua", slug: "lua" },
  { name: "Scala", slug: "scala" },
  { name: "PHP", slug: "php" },
  { name: "C#", slug: "csharp" },
  { name: "Perl", slug: "perl" },
  { name: "Go", slug: "go" },
  { name: "Visual Basic (VB.NET)", slug: "vb" },
  { name: "TypeScript", slug: "typescript" },
  { name: "Kotlin", slug: "kotlin" },
  { name: "Pascal", slug: "pascal" },
  { name: "Rust", slug: "rust" },
  { name: "Swift", slug: "swift" },
  { name: "Objective-C", slug: "objectivec", theme: "objective-c" },
  { name: "CoffeeScript", slug: "coffeescript" },
  { name: "HTML", slug: "html" },
  { name: "MySQL", slug: "mysql" },
  { name: "MariaDB", slug: "mariadb", theme: "sql" },
  { name: "Microsoft SQL Server", slug: "sqlserver", theme: "sql" },
  { name: "SQLite", slug: "sqlite", theme: "sql" },
  { name: "Oracle Database", slug: "oracle-database", theme: "sql" },
  { name: "Redis", slug: "redis" },
  { name: "MongoDB", slug: "mongodb", theme: "objective-c" },
];

export default languages;
